### ISSUE TITLE
BTC addresses generated are wrong.

### ISSUE THREAD

**Issue by nahtnam** [snitko/straight-server#13]
Hey!

I think I found a bug.

Problem: Sent BTC to address that was generated, but it is not showing up.

Steps:
Install Electrum (2.0.4) and create a new wallet.
Then in the menu, go to `Wallet > Mater Public Key`
Use that public key in the straight config.
Create an order ($1 in my case), and pay it.
Check electrum, and the order does **not** appear.

Any help would be appreciated.

**Comment by snitko** [comment]
Ok, so to make this clear, Straight generated the address out of the pubkey, you sent money there, but never received them?

There maybe a number of reasons. One reason may be that you used too high of an id to create a new order and BIP32 wallets usually have a lookup constraint. It doesn't check, let's say, 100-th address unless at least one of the previous 99 address contains bitcoins.

The other reason is that transaction may still be unconfirmed.

To figure this out, can you give me the following info:
1. transaction id
2. payment address
3. id used to create a new order

I don't think the problem is that the address itself is wrong, that is highly unlikely.

**Comment by nahtnam** [comment]
1. https://blockchain.info/tx/453a30449c3cb3bfd97bc760d5524a06ea0ed360372492b1a6448eb0403d00ce

2. https://blockchain.info/address/1JW8dsiJr1ZedCuxWL4M5jBCDQothGUgTQ

3. #27

Electrum is only showing 20 receive addresses (http://i.imgur.com/o0n0OQe.png). Do you know how to get it to generate more?

**Comment by snitko** [comment]
Ok, I think I know what's going on. Electrum generates addresses using `m/0/0` notation and it's different in Straight. I might have to change that. Will let you know asap.

**Comment by nahtnam** [comment]
Thanks for checking it out.

**Comment by nahtnam** [comment]
Any update?

**Comment by snitko** [comment]
Yes, this commit should fix it: https://github.com/snitko/straight/commit/3f43701d24c315e75c18eecb11ba6fefb7bb5772

Note that the changes are made in `straight`, not `straight-server`. You will need to manually update `straight` lib on your machine by pulling the changes and then running `rake build` and `rake install`.

**Comment by snitko** [comment]
Also, you might want to start counting your orders from 1 again. Otherwise, Electrum might not see it (27 is above the standard 20 addresses Electrum generates. It will generate more when the previous ones are getting filled.

**Comment by nahtnam** [comment]
Will do. Thanks!
