### ISSUE TITLE
After restarting, Orders are not rechecked in development

### ISSUE THREAD

**Issue by nahtnam** [snitko/straight-server#5]
Hey!

Suppose we start a development server by running `straight-server`, and we create the order 1. It will occasionally say `checking the status of order 1`. If we shut down the server and restart it, it doesnt ever check the status of order 1 again. It only checks any orders made after the new server instance is started.

Is this a development only thing or is it also an issue in production?

@snitko

**Comment by nahtnam** [comment]
@snitko Any update?

**Comment by snitko** [comment]
Not yet, but it's in my TODO list.

**Comment by snitko** [comment]
Funcionaity added: https://github.com/snitko/straight-server/commit/1cdb2650c1a1334f4e39f6cc56f0fcc0a2e9d2ea

**Comment by snitko** [comment]
Also, please note:

If you shut the server down and the start it again, all unresolved orders (status < 2 and non-expired)
are automatically picked up and the server starts checking on them again until they expire. Please note
that you'd need to make sure you client side reconnects to the order's websocket again. This is because
on server shutdown, all websocket connections are closed, therefore, there's no way to automatically restore them. It is thus client's responsibility to check when websocket is closed, then periodically try to connect to it again.

**Comment by nahtnam** [comment]
Awesome! I use callbacks + signature so this doesnt pertain to me but make sure you put this in the readme so others know.
